# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Name', models.CharField(max_length=250)),
                ('DOB', models.DateField()),
                ('Street', models.CharField(max_length=250)),
                ('District', models.CharField(max_length=250)),
                ('State', models.CharField(max_length=250)),
                ('Pincode', models.BigIntegerField()),
                ('UID', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
    ]
