# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Persons',
        ),
    ]
