# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180118_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='UID',
            field=models.AutoField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
