# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180118_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Pincode',
            field=models.CharField(max_length=8),
        ),
    ]
