# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
