# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
